name: 发布测试

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
        sudo -E apt-get -y install tar
        sudo  tar -zcvf /mnt/openwrt-master/* ./ceshi.tar.gz

       - name: Upload to Release
         uses: JasonEtco/upload-to-release@v0.1.1
         with:
          args: ceshi.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
