name: 发布测试

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Gzip
        run: |
          tar --warning=no-file-changed -czvf release.tar.gz ./package
          
      - uses: majkrzak/create-release@master
        with:
            token: ${{secrets.RELEASES_TOKEN}}
            name: Openwrt latest for psg1218a daily build 模拟发布
            code: latest
            prerelease: flase
            assets: >
                release.tar.gz:release.tar.gz:
          

