name: 发布测试

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Gzip
        run: |
          tar --warning=no-file-changed -czvf release.tar.gz ./package
          
      - name: Upload to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          branch: master
          name: OpenWrt PSG1218a firmware
          args: release.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
